spring.application.name=zauction
spring.profiles.active=mysql

security.cors-origin=*
security.api-header=X-API-KEY
security.api-secret=eVfMSi4Qmuh0utHbZ28IAw
security.cookie-name=Authorization
security.cookie-validity=43200