@startuml

package ch.zucchinit.zauction {
    class SpringApplication
    class ZAuctionApplication {
        +main(String[]): void
    }
    "ZAuctionApplication" --> "SpringApplication"

    package Auth {
        interface UserRepository<extends JARepository<User, Long>>{
            findByEmail(String email): Optional<User>
            existsByEmail(String email): boolean
        }
        interface TokenRepository<extends JARepository<Token, Long>>{
            deleteByExpireDateBefore(LocalDateTime: date): void
        }
        class AuthDTO
        class AuthController {
            -userService: UserService
            -tokenService: TokenService
            +register(HttpServletResponse response, AuthDTO.UserRegister register): AuthDTO.UserProfile
            +login(HttpServletResponse response, AuthDTO.UserLogin login): AuthDTO.UserProfile
            +unregister(HttpServletResponse response): void
            +me(): AuthDTO.UserProfile
            +getAccount(): AuthDTO.UserAccount
            +updateAccount(AuthDTO.UserAccount userAccount): AuthDTO.UserAccount
            +resetPassword(AuthDTO.UserResetPassword userResetPassword): void
        }
        class UserService {
            -userRepository: UserRepository
            -passwordEncoder: BCryptPasswordEncoder
            +getUserFromContext(): User
            +getUserProfile(User user): AuthDTO.UserProfile
            +getUserAccount(User user): AuthDTO.UserAccount
            +findUserByEmailAndPassword(String email, String password): User
            +createUser(AuthDTO.UserRegister register): User
            +updateUser(AuthDTO.UserAccount userAccount): AuthDTO.UserAccount
            +resetPassword(AuthDTO.UserResetPassword userResetPassword): void
        }
        class TokenService {
            +tokenMinutesValidity: Integer
            -tokenRepository: TokenRepository
            +getCookieToken(String tokenValue): Cookie
            +extractCookieToken(Cookie[] cookies): Cookie
            +deleteCookieToken(): Cookie
            +registerToken(User user): void
            +findTokenById(String tokenValue): Token
            +unregisterToken(Token token): void
            +purgeExpiredTokens(): void
        }

        "AuthController" --> "UserService"
        "AuthController" --> "TokenService"
        "AuthController" --> "AuthDTO"
        "UserService" --> "UserRepository"
        "UserService" --> "AuthDTO"
        "TokenService" --> "TokenRepository"
    }

    package Category {
        interface CategoryRepository<extends JARepository<Category, Long>> {
            -findByParentIsNull: Category[]
        }
        class CategoryController {
            -categoryService: CategoryService
            +all(): Category[]
        }
        class CategoryService {
            -categoryRepository: CategoryRepository
            +findAll(): Category[]
            +getChildIds(Category category, Long ids[]): Long[]
            +getReverseCategories(Long categoryId): Category[]
        }

        "CategoryController" --> "CategoryService"
        "CategoryService" --> "CategoryRepository"
    }

    package Lot {
        interface LotRepository<extends JARepository<Lot, Long>>
        class LotDTO
        class LotController {
            -lotService: LotService
            +paginate(Integer page, Integer take, Category category, String search): LotDTO.LotPaginatedThumbnail
            +one(Long id): LotDTO.LotDetails
            +auctionsPerPeriod(Long id, String period): AuctionDTO.AuctionPrice[]
            +requestAuction(Long id, AuctionDTO.AuctionRequest auctionRequest: AuctionDTO.AuctionPrice
        }
        class LotService {
            -lotRepository: LotRepository
            -categoryService: CategoryService
            -auctionService: AuctionService
            +findByPageWithCategoryAndSearch(Integer page, Integer take, Category category, String search): LotDTO.LotPaginatedThumbnail
            +findById(Long id): LotDTO.LotDetails
            +getLotThumbnail(Lot lot): LotDTO.LotThumbnail
            +getLotDetails(Lot lot): LotDTO.LotDetails
        }
        class LotSpecifications {
            {static}isFinished() : Specification<Lot>
            {static}hasCategoryId(Long id) : Specification<Lot>
            {static}multiFieldSearch(String keyword) : Specification<Lot>
        }

        "LotController" --> "LotService"
        "LotController" --> "LotDTO"
        "LotService" --> "LotRepository"
        "LotService" --> "LotDTO"
        "LotService" --> "LotSpecifications"
    }
    "Lot.LotController" --> "Auction.AuctionDTO"
    "Lot.LotService" --> "Category.CategoryService"
    "Lot.LotService" --> "Auction.AuctionService"

    package Auction {
        interface AuctionRepository<extends JARepository<Auction, Long>> {
            findByLotAndDateAfterOrderByDateDesc(Lot lot, LocalDateTime date): Auction[]
            existsAuctionByLotAndPriceGreaterThanEqual(Lot lot, BigDecimal price): boolean
        }
        class AuctionDTO
        class AuctionService {
            -auctionRepository: AuctionRepository
            -getAuctionPrice(Auction auction): AuctionDTO.AuctionPrice
            +createAuction(Lot lot, AuctionDTO.AuctionRequest): AuctionDTO.AuctionPrice
            +findAuctionsByPeriod(Lot lot, AuctionDTO.TimePeriod period): AuctionDTO.AuctionPrice[]
            -getPeriodKey(AuctionDTO.TimePeriod timePeriod): LocalDateTime
        }

        "AuctionService" --> "AuctionRepository"
        "AuctionService" --> "AuctionDTO"
   }

    package Exceptions {
        exception "ResourceNotFound"
        exception "NotAuthorized"
        class "ExceptionsDTO"
        class ExceptionsAdvice {
            +userNotAuthorizedHandler: void
            +resourceNotFoundHandler: void
            +validationErrorHandler : ExceptionsDTO
            +unknownErrorHandler: ExceptionsDTO
        }

        "ExceptionsAdvice" --> "ResourceNotFound"
        "ExceptionsAdvice" --> "NotAuthorized"
        "ExceptionsAdvice" --> "ExceptionsDTO"
    }

    package Security {
        class SecurityConfig {
            -corsConfigurationSource: CorsConfigurationSource
            +securityFilterChain: SecurityFilterChain
        }

        class UserAuthTokenFilter {
            {static} authCookieName: String
            -tokenService: TokenService
            #doFilterInternal(): void
        }

        class APIBaseTokenFilter {
            -API_HEADER: String
            -API_SECRET: String
            #doFilterInternal(): void
        }

        "SecurityConfig" --> "UserAuthTokenFilter"
        "SecurityConfig" --> "APIBaseTokenFilter"
    }
    "Security.UserAuthTokenFilter" --> "Auth.TokenService"

    package Utils {
        class FieldUpdater {
            {static}updateIfChanged<T>(Supplier<T> getter, Consumer<T> setter, T value): void
        }

        class S3Connector {
            -s3client: s3Client
            +uploadMedias(Long id)
            +getUrls(Long id): String[]
        }
        note top: not used yet
    }
    "Auth.UserService" --> "Utils.FieldUpdater"
    "Lot.LotService" --> "Utils.S3Connector"
}

@enduml