@startuml

package ch.zucchinit.zauction {
    class SpringApplication
    class ZAuctionApplication {
        +main(String[]): void
    }
    "ZAuctionApplication" --> "SpringApplication"

    package Category {
        interface CategoryRepository<extends JARepository<Category, Long>>
        class CategoryController {
            -categoryService: CategoryService
            +all(): Category[]
        }
        class CategoryService {
            -categoryRepository: CategoryRepository
            +findAll(): Category[]
        }

        "CategoryController" --> "CategoryService"
        "CategoryService" --> "CategoryRepository"
    }

    package Lot {
        interface LotRepository<extends JARepository<Lot, Long>>
        class LotController {
            -lotService: LotService
            +paginate(Integer page, Integer take, Category category, String search): LotThumbnail[]
            +one(Long id): LotDetails
        }
        class LotService {
            -lotRepository: LotRepository
            +findByPageWithCategoryAndSearch(Integer page, Integer take, Category category, String search): LotThumbnail[]
            +findById(Long id): LotDetails
        }

        "LotController" --> "LotService"
        "LotService" --> "LotRepository"
    }

    package Auction {
        interface AuctionRepository<extends JARepository<Auction, Long>>
   }

    package Exceptions {
        exception "ResourceNotFound"
        exception "BadRequest"
        class ExceptionsAdvice {
            + handleValidationErrors: Map<String, String[]>
        }

        "ResourceNotFound" --> "ExceptionsAdvice"
        "BadRequest" --> "ExceptionsAdvice"
    }

    class S3Connector {
        -s3client: s3Client
        +uploadMedias(Long id)
        +getUrls(Long id): String[]
    }
    "LotService" --> "S3Connector"
}

@enduml