@startuml

package AuthDTO {
    class UserProfile {
        -firstName: String
        -lastName: String
        -balance: BigDecimal
    }

    class UserAccount {
        -firstName: String
        -lastName: String
        -email: String
        -phone: String
        -address: String
        -city: String
        -zipCode: String
    }

    class UserLogin {
        -email: String
        -password: String
    }

    class UserRegister {
        -email: String
        -firstName: String
        -lastName: String
        -password: String
    }

    class UserResetPassword {
        -oldPassword: String
        -newPassword: String
    }
}

package LotDTO {
    class LotPaginatedThumbnail {
        -content: LotThumbnail[]
        -page: Integer
        -take: Integer
        -total: Long
    }

    class LotThumbnail {
        -id: Long
        -name: String
        -location: String
        -initial_price: BigDecimal
        -last_price: BigDecimal
        -thumbnail: String
    }

    class LotDetails {
        -id: Long
        -name: String
        -description: String
        -location: String
        -initial_price: BigDecimal
        -last_price: BigDecimal
        -medias: String[]
        -open_date: LocalDateTime
        -award_date: LocalDateTime
        -close_date: LocalDateTime
        -first_auction_date: BigDecimal
        -last_auction_date: BigDecimal
        -last_bidder: boolean
        -category: Category[]
        -auctions: Auction[]
    }
}

package AuctionDTO {
    enum TimePeriod {
        -ALL
        -YEAR
        -SEMESTER
        -QUARTER
        -MONTH
        -WEEK
        -DAY
    }

    class AuctionPrice {
        -date: LocalDateTime
        -price: BigDecimal
    }

    class AuctionRequest {
        -price: Decimal
    }

    class AuctionResponse {
        -date: LocalDateTime
        -price: BigDecimal
        -newBalance: BigDecimal
    }
}
@enduml