@startuml

actor User

cloud "Web" as Web

folder "Infra" {
    node "Proxy" as Proxy
    node "Serveur Applicatif" as AppServer {
        node "Frontend" as Frontend
        node "Backend" as Backend
    }
    database "Database" as Database
}

interface "Amazon S3" as AmazonS3

User -- Web : HTTP/HTTPS (80/443)
Web -- Proxy : HTTP/HTTPS (80/443)
Proxy -- Frontend : HTTP (80)
Frontend -- Backend : HTTP (8080)
Backend -- Database : TCP (5432)
Frontend -- AmazonS3 : HTTPS (443)
Backend -- AmazonS3 : HTTPS (443)

@enduml
